version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3111:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3112:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000  # Use internal Docker network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
